
package packageClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Example", targetNamespace = "http://ExampleSoap.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Example {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.DivisionResponse")
    @Action(input = "http://ExampleSoap.example.com/Example/divisionRequest", output = "http://ExampleSoap.example.com/Example/divisionResponse")
    public int division(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "produit", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.Produit")
    @ResponseWrapper(localName = "produitResponse", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.ProduitResponse")
    @Action(input = "http://ExampleSoap.example.com/Example/produitRequest", output = "http://ExampleSoap.example.com/Example/produitResponse")
    public int produit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustraction", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.Soustraction")
    @ResponseWrapper(localName = "soustractionResponse", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.SoustractionResponse")
    @Action(input = "http://ExampleSoap.example.com/Example/soustractionRequest", output = "http://ExampleSoap.example.com/Example/soustractionResponse")
    public int soustraction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "somme", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.Somme")
    @ResponseWrapper(localName = "sommeResponse", targetNamespace = "http://ExampleSoap.example.com/", className = "packageClient.SommeResponse")
    @Action(input = "http://ExampleSoap.example.com/Example/sommeRequest", output = "http://ExampleSoap.example.com/Example/sommeResponse")
    public int somme(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
